// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/about" | "/articles" | "/articles/[slug]" | "/articles/complete-car-shades-guide-jeddah-2024" | "/audit" | "/contact" | "/dashboard" | "/dashboard/projects" | "/dashboard/projects/[id]" | "/dashboard/projects/[id]/edit" | "/dashboard/projects/add" | "/dashboard/settings" | "/faq" | "/login" | "/manual-indexing" | "/portfolio" | "/portfolio/[id]" | "/portfolio/reviews" | "/privacy" | "/quote" | "/search" | "/seo-monitor" | "/services/byoot-shaar" | "/services/khayyam" | "/services/landscaping" | "/services/mazallat" | "/services/pergolas" | "/services/renovation" | "/services/sandwich-panel" | "/services/sawater" | "/terms"
type AppRouteHandlerRoutes = "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/verify" | "/api/dashboard/stats" | "/api/healthcheck" | "/api/indexnow" | "/api/manual-indexing/test" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/comments" | "/api/projects/[id]/interactions" | "/api/projects/create" | "/api/reviews" | "/api/search" | "/api/seo/indexing-status" | "/api/site-audit" | "/api/sitemap/auto-refresh" | "/api/sitemap/refresh" | "/api/upload" | "/api/webhook/content-updated" | "/robots.txt" | "/sitemap-articles.xml" | "/sitemap-images.xml" | "/sitemap-index.xml" | "/sitemap-projects.xml" | "/sitemap.xml"
type PageRoutes = "/" | "/_app" | "/home"
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = "/"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_app": {}
  "/about": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/verify": {}
  "/api/dashboard/stats": {}
  "/api/healthcheck": {}
  "/api/indexnow": {}
  "/api/manual-indexing/test": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/comments": { "id": string; }
  "/api/projects/[id]/interactions": { "id": string; }
  "/api/projects/create": {}
  "/api/reviews": {}
  "/api/search": {}
  "/api/seo/indexing-status": {}
  "/api/site-audit": {}
  "/api/sitemap/auto-refresh": {}
  "/api/sitemap/refresh": {}
  "/api/upload": {}
  "/api/webhook/content-updated": {}
  "/articles": {}
  "/articles/[slug]": { "slug": string; }
  "/articles/complete-car-shades-guide-jeddah-2024": {}
  "/audit": {}
  "/contact": {}
  "/dashboard": {}
  "/dashboard/projects": {}
  "/dashboard/projects/[id]": { "id": string; }
  "/dashboard/projects/[id]/edit": { "id": string; }
  "/dashboard/projects/add": {}
  "/dashboard/settings": {}
  "/faq": {}
  "/home": {}
  "/login": {}
  "/manual-indexing": {}
  "/portfolio": {}
  "/portfolio/[id]": { "id": string; }
  "/portfolio/reviews": {}
  "/privacy": {}
  "/quote": {}
  "/robots.txt": {}
  "/search": {}
  "/seo-monitor": {}
  "/services/byoot-shaar": {}
  "/services/khayyam": {}
  "/services/landscaping": {}
  "/services/mazallat": {}
  "/services/pergolas": {}
  "/services/renovation": {}
  "/services/sandwich-panel": {}
  "/services/sawater": {}
  "/sitemap-articles.xml": {}
  "/sitemap-images.xml": {}
  "/sitemap-index.xml": {}
  "/sitemap-projects.xml": {}
  "/sitemap.xml": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
